name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/package-code-quality

trigger:
  branches:
    include:
      - "*"

pr:
  branches:
    include:
      - main

variables:
  - group: dsi-global

stages:
  - stage: codeScan
    displayName: "Scan tools"
    jobs:
      - template: pipeline/scanTools.yml@devopsTemplates
        parameters:
          useRevisedLinting: true
          AppDeploy: true

  - stage: publishPackage
    displayName: "Publish package"
    dependsOn:
      - codeScan
    condition: in(dependencies.codeScan.result, 'Succeeded', 'Skipped')
    jobs:
      - template: /pipeline/buildAzurePackageArtifactV2.yml@devopsTemplates
        parameters:
          applicationName: validation
          nodeVersionSpec: "18.17.0"
