name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: main

trigger:
  branches:
    include:
      - "*"

pr: none

variables:
  - group: dsi-global

stages:
  - stage: prepare
    displayName: Prepare
    jobs:
      - template: pipeline/node-project/checks.yml@devopsTemplates
        parameters:
          nodeVersionSpec: 22.11.0

  - stage: publishPackage
    displayName: Publish Package
    dependsOn:
      - prepare
    condition: in(dependencies.prepare.result, 'Succeeded', 'Skipped')
    jobs:
      - template: pipeline/node-project/publishPackage.yml@devopsTemplates
        parameters:
          nodeVersionSpec: 22.11.0