language: node_js
node_js:
- '8.4'
notifications:
  slack:
    secure: pV3YDyM9HkiaHoVi88fUZ0XTaEekbWxtWGGRpvqKZ0mTbS6RpE8ryah4FfF13GiqfBLhcGgV0D9FMXzbs2Ix44rceCRcAjPL5UFuo4PDJ8eAwGkhnm9wALtTDHIoVbyX5US0kEXb1eEw3iN01SdEpQ30m7B/JAZtAIe8FogFkTOrAuiW4kQ/LLU1G9Bh0mNRCSrKvru6I4/NWtO57CaoGiOQdd8kEzlmGrMQUX2nhFpaZfZZELQx+SF+Um6zdrlI5EYxpQ5sOMvsNlGlS/+hyWWyh02akT/gBXya4OiyS27HWrdv4bJ48KJ0F7aVBB1/BY8q+jfwmnJof3Q51ts3rL1Fm4ZYWXRVAC5u0TixYinGC6dHQxo79rYjOpbvpoqzAT6gTwzb4TSsTdZLU8zscw4GNqN4xdwSKW8+jAKbHXxi9+lwS5SIcgVsnS4WbqLh33yT4DmfwJ8C9xCq2mAe3fe49AIxheFPYrfQehCPjcRmchVvanjZEGxkSuS44otAzeivR4QGkXYSC67x0zfpbCglPkehhsZzQbJIC7U+1yGoLttA41EkJ4WHzqyADSAZXLY8UHaNpT61SGFjH6ToNeMJOcY+NlWVc+YMs5F1cmT1NbhZucVAkCr97d9vAuDFb4di/7G2o8+g5gPoyk55KeObk9s1mHE9aLkee8ouQbs=
  on_success: never
  on_failure: always